import type { CitationRef, MissionEvent } from '../../mission-core/index.ts'

export interface Apollo11EventSeed {
  id: string
  label: string
  metSeconds: number
  tier: MissionEvent['tier']
  precision: NonNullable<MissionEvent['precision']>
  citations: CitationRef[]
}

const missionReport34 = (note?: string): CitationRef[] => [
  {
    sourceId: 'NASA-A11-MR',
    pages: '3-4',
    locator: 'Table 3-I',
    note,
  },
]

const missionReport35 = (note?: string): CitationRef[] => [
  {
    sourceId: 'NASA-A11-MR',
    pages: '3-5',
    locator: 'Table 3-I',
    note,
  },
]

export const apollo11EventSeeds = [
  {
    id: 'a11-liftoff',
    label: 'LIFTOFF',
    metSeconds: 0.6,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34('Range zero precedes this row.'),
  },
  {
    id: 'a11-sic-outboard-cutoff',
    label: 'S-IC OUTBOARD ENGINE CUTOFF',
    metSeconds: 161.7,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Engine cutoff; not physical stage separation.'),
  },
  {
    id: 'a11-sic-sii-separation',
    label: 'S-IC / S-II SEPARATION COMMAND',
    metSeconds: 162.3,
    tier: 'major',
    precision: 'tenth-second',
    citations: [
      { sourceId: 'NASA-A11-SATV-FE', pages: '41, 63', locator: 'Tables 2-2 Event 27 and 4-3' },
    ],
  },
  {
    id: 'a11-sii-ignition-command',
    label: 'S-II ENGINE IGNITION COMMAND',
    metSeconds: 163,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Source identifies this as a command.'),
  },
  {
    id: 'a11-les-jettison',
    label: 'LAUNCH ESCAPE TOWER JETTISON',
    metSeconds: 197.9,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34(),
  },
  {
    id: 'a11-sii-cutoff',
    label: 'S-II ENGINE CUTOFF',
    metSeconds: 548.3,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Engine cutoff; not physical stage separation.'),
  },
  {
    id: 'a11-sii-sivb-separation',
    label: 'S-II / S-IVB SEPARATION COMMAND',
    metSeconds: 549,
    tier: 'major',
    precision: 'tenth-second',
    citations: [
      { sourceId: 'NASA-A11-SATV-FE', pages: '42, 63', locator: 'Tables 2-2 Event 46 and 4-3' },
    ],
  },
  {
    id: 'a11-sivb-first-ignition',
    label: 'S-IVB FIRST IGNITION COMMAND',
    metSeconds: 552.2,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34(),
  },
  {
    id: 'a11-sivb-first-cutoff',
    label: 'S-IVB FIRST CUTOFF',
    metSeconds: 699.3,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34(),
  },
  {
    id: 'a11-tli-ignition',
    label: 'TRANSLUNAR INJECTION',
    metSeconds: 9856.2,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-csm-sivb-separation',
    label: 'CSM / S-IVB SEPARATION',
    metSeconds: 11824.6,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34(),
  },
  {
    id: 'a11-first-docking',
    label: 'FIRST DOCKING',
    metSeconds: 12243.1,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34(),
  },
  {
    id: 'a11-spacecraft-ejection',
    label: 'SPACECRAFT EJECTION',
    metSeconds: 15419.1,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34(
      'This source row does not independently establish a distinct LM-extraction-complete MET.',
    ),
  },
  {
    id: 'a11-sivb-separation-maneuver',
    label: 'SEPARATION MANEUVER FROM S-IVB',
    metSeconds: 16801.8,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-mcc1-ignition',
    label: 'MIDCOURSE CORRECTION 1',
    metSeconds: 96298.7,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-loi-ignition',
    label: 'LUNAR ORBIT INSERTION',
    metSeconds: 272990.4,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-lunar-orbit-circularization',
    label: 'LUNAR ORBIT CIRCULARIZATION',
    metSeconds: 288696.8,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-undocking',
    label: 'COLUMBIA / EAGLE UNDOCKING',
    metSeconds: 360720,
    tier: 'major',
    precision: 'second',
    citations: missionReport34('Integer-second source value.'),
  },
  {
    id: 'a11-lm-separation-maneuver',
    label: 'SEPARATION MANEUVER FROM LM',
    metSeconds: 362392.9,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-doi-ignition',
    label: 'DESCENT ORBIT INSERTION',
    metSeconds: 365774,
    tier: 'major',
    precision: 'second',
    citations: missionReport34('Integer-second source value; engine ignition time.'),
  },
  {
    id: 'a11-pdi-ignition',
    label: 'POWERED DESCENT INITIATION',
    metSeconds: 369185.2,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-touchdown',
    label: 'LUNAR LANDING / TOUCHDOWN',
    metSeconds: 369939.9,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34(),
  },
  {
    id: 'a11-lm-hatch-open',
    label: 'LM HATCH OPEN',
    metSeconds: 392853,
    tier: 'minor',
    precision: 'second',
    citations: missionReport34('Integer-second source value.'),
  },
  {
    id: 'a11-first-step',
    label: 'FIRST STEP',
    metSeconds: 393855,
    tier: 'major',
    precision: 'source-rounded',
    citations: [
      {
        sourceId: 'NASA-APOLLO-NUMBERS',
        pages: '104, 118',
        locator: 'Apollo 11 narrative and timeline table',
        note: 'Canonical 109:24:15; other sources differ by several seconds.',
      },
    ],
  },
  {
    id: 'a11-lm-hatch-close',
    label: 'LM HATCH CLOSED',
    metSeconds: 401953,
    tier: 'minor',
    precision: 'second',
    citations: missionReport34('Integer-second source value.'),
  },
  {
    id: 'a11-lunar-liftoff',
    label: 'LUNAR LIFTOFF / APS IGNITION',
    metSeconds: 447720.8,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-csi-ignition',
    label: 'COELLIPTIC SEQUENCE INITIATION',
    metSeconds: 451176,
    tier: 'minor',
    precision: 'second',
    citations: missionReport34('Integer-second source value; engine ignition time.'),
  },
  {
    id: 'a11-cdh-ignition',
    label: 'CONSTANT DIFFERENTIAL HEIGHT',
    metSeconds: 454669.6,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-tpi-ignition',
    label: 'TERMINAL PHASE INITIATION',
    metSeconds: 457431.8,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport34('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-lm-csm-docking',
    label: 'EAGLE / COLUMBIA DOCKING',
    metSeconds: 460980,
    tier: 'major',
    precision: 'second',
    citations: missionReport35('Integer-second source value.'),
  },
  {
    id: 'a11-ascent-stage-jettison',
    label: 'ASCENT STAGE JETTISON',
    metSeconds: 468571.2,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport35(),
  },
  {
    id: 'a11-ascent-stage-separation-maneuver',
    label: 'SEPARATION MANEUVER FROM ASCENT STAGE',
    metSeconds: 469801,
    tier: 'minor',
    precision: 'second',
    citations: missionReport35('Integer-second source value; engine ignition time.'),
  },
  {
    id: 'a11-tei-ignition',
    label: 'TRANSEARTH INJECTION',
    metSeconds: 487422.3,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport35('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-mcc2-ignition',
    label: 'MIDCOURSE CORRECTION 2',
    metSeconds: 541797.4,
    tier: 'minor',
    precision: 'tenth-second',
    citations: missionReport35('Asterisk in source denotes engine ignition time.'),
  },
  {
    id: 'a11-cm-sm-separation',
    label: 'CM / SM SEPARATION',
    metSeconds: 701352.7,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport35(),
  },
  {
    id: 'a11-entry-interface',
    label: 'ENTRY INTERFACE',
    metSeconds: 702185.7,
    tier: 'major',
    precision: 'tenth-second',
    citations: missionReport35(),
  },
  {
    id: 'a11-splashdown',
    label: 'SPLASHDOWN',
    metSeconds: 703115,
    tier: 'major',
    precision: 'second',
    citations: missionReport35('Source row says Landing; label disambiguated from lunar landing.'),
  },
] satisfies Apollo11EventSeed[]
