export const mission = {
  title: 'APOLLO 11 MISSION ARCHIVE',
  mission: 'APOLLO 11',
  launchVehicle: 'AS-506',
  csm: 'CSM-107 COLUMBIA',
  lm: 'LM-5 EAGLE',
  dates: '16–24 JUL 1969',
  crew: [
    'NEIL A. ARMSTRONG — COMMANDER',
    'MICHAEL COLLINS — COMMAND MODULE PILOT',
    'EDWIN E. ALDRIN JR. — LUNAR MODULE PILOT',
  ],
  identityCitation: 'NASA-A11-MR · Apollo 11 Mission Report',
}

export const sections = [
  ['00', 'Mission Index'],
  ['01', 'Mission Objectives'],
  ['02', 'Crew & Flight Roles'],
  ['03', 'As-Flown Timeline'],
  ['04', 'Flight Architecture'],
  ['05', 'Saturn V / AS-506'],
  ['06', 'Columbia & Eagle'],
  ['07', 'Guidance & Computing'],
  ['08', 'Mission Control & Network'],
  ['09', 'Powered Descent & Landing'],
  ['10', 'Lunar Surface Operations'],
  ['11', 'Rendezvous, Return & Recovery'],
  ['12', 'Media & Source Room'],
]

export const events = [
  {
    id: 'a11-liftoff',
    met: '000:00:00.6',
    seconds: 0.6,
    phase: 'ASCENT',
    title: 'LIFTOFF',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-4 · PDF p. 18',
    evidence: 'ACTUAL',
    view: 'launch',
    note: 'Mission Report records liftoff at MET 00:00:00.6.',
  },
  {
    id: 'a11-sic-sii-separation',
    met: '000:02:42.3',
    seconds: 162.3,
    phase: 'ASCENT',
    title: 'S-IC / S-II SEPARATION COMMAND',
    source: 'NASA-A11-SATV-FE',
    locator: 'Table 2-2 Event 27 · PDF p. 41; Table 4-3 · PDF p. 63',
    evidence: 'ACTUAL',
    view: 'staging-one',
    note: 'Direct RANGE TIME ACTUAL. No separate physical-severance timestamp is claimed.',
  },
  {
    id: 'a11-sii-sivb-separation',
    met: '000:09:09.0',
    seconds: 549,
    phase: 'ASCENT',
    title: 'S-II / S-IVB SEPARATION COMMAND',
    source: 'NASA-A11-SATV-FE',
    locator: 'Table 2-2 Event 46 · PDF p. 42; Table 4-3 · PDF p. 63',
    evidence: 'ACTUAL',
    view: 'staging-two',
    note: 'Direct RANGE TIME ACTUAL. Event 48 is 550.4 s and is not this event.',
  },
  {
    id: 'a11-tli-ignition',
    met: '002:44:16.2',
    seconds: 9856.2,
    phase: 'TLI / EXTRACTION',
    title: 'TRANSLUNAR INJECTION',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-4 · PDF p. 18',
    evidence: 'ACTUAL',
    view: 'earth-moon',
    note: 'Mission Report engine ignition time.',
  },
  {
    id: 'a11-loi-ignition',
    met: '075:49:50.4',
    seconds: 272990.4,
    phase: 'LUNAR ORBIT',
    title: 'LUNAR ORBIT INSERTION',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-4 · PDF p. 18',
    evidence: 'ACTUAL',
    view: 'lunar-orbit',
    note: 'Mission Report engine ignition time.',
  },
  {
    id: 'a11-pdi-ignition',
    met: '102:33:05.2',
    seconds: 369185.2,
    phase: 'POWERED DESCENT',
    title: 'POWERED DESCENT INITIATION',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-4 · PDF p. 18',
    evidence: 'ACTUAL',
    view: 'descent',
    note: 'Mission Report engine ignition time. The drawn path is schematic.',
  },
  {
    id: 'a11-touchdown',
    met: '102:45:39.9',
    seconds: 369939.9,
    phase: 'LUNAR SURFACE OPS',
    title: 'LUNAR LANDING / TOUCHDOWN',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-4 · PDF p. 18',
    evidence: 'ACTUAL',
    view: 'surface',
    note: 'Event time is actual. The external Eagle view is reconstructed/schematic.',
  },
  {
    id: 'a11-lunar-liftoff',
    met: '124:22:00.8',
    seconds: 447720.8,
    phase: 'ASCENT / RENDEZVOUS',
    title: 'LUNAR LIFTOFF',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-4 · PDF p. 18',
    evidence: 'ACTUAL',
    view: 'lunar-ascent',
    note: 'Mission Report engine ignition time. External view is reconstructed.',
  },
  {
    id: 'a11-splashdown',
    met: '195:18:35',
    seconds: 703115,
    phase: 'RECOVERY',
    title: 'SPLASHDOWN',
    source: 'NASA-A11-MR',
    locator: 'Table 3-I · printed p. 3-5 · PDF p. 19',
    evidence: 'ACTUAL',
    view: 'recovery',
    note: 'Mission Report landing time, labelled splashdown here to avoid ambiguity.',
  },
]

export const sources = {
  'NASA-A11-MR': {
    title: 'Apollo 11 Mission Report',
    detail: 'MSC-00171 · primary post-mission source for the selected event records.',
    path: 'assets/raw/NASA-A11-MR.pdf',
  },
  'NASA-A11-SATV-FE': {
    title: 'Apollo 11 Saturn V Flight Evaluation',
    detail: 'MPR-SAT-FE-69-9 / NASA-TM-X-62558 · direct Table 2-2 and Table 4-3 staging records.',
    path: 'assets/raw/NASA-A11-SATV-FE.pdf',
  },
  'NASA-A11-MOON-VIEW': {
    title: 'Apollo 11 — View of the Moon',
    detail: 'AS11-44-6665 · transearth evidence plate; not an approach or LOI view.',
    path: 'assets/raw/NASA-A11-MOON-VIEW.jpg',
  },
  'NASA-A11-LANDING-SITE-LRO': {
    title: 'Apollo 11 Landing Site, LROC',
    detail: 'Modern orbital image of the landing site; not a 1969 surface photograph.',
    path: 'assets/raw/NASA-A11-LANDING-SITE-LRO.jpg',
  },
}
